// Song content generator - a reusable little synth + Standard MIDI File
// writer for producing a chart's .wav/.mid pairs from code instead of real
// recordings: square/triangle/bell/bass tones for melodic clips, noise+sine
// drum hits for percussion, all mixed and written as plain 16-bit mono PCM
// WAV, plus (for judged clips) a matching note chart using the engine's
// four fixed lane pitches (c_LaneMidiPitches in src/LaneConfig.h - keep this
// in sync if that ever changes). Deterministic: the noise generator is a
// seeded LCG, so re-running produces byte-identical output.
//
// Not wired into CMakeLists.txt (it has no dependency on the engine at
// all, just the C++ standard library) - compile and run it directly:
//   g++ -O2 -std=c++20 -o song_gen.exe tools/SongGenerator.cpp
//   ./song_gen.exe        (run from the repo root - paths are relative to it)
//
// Everything above main() is the reusable part (WAV/MIDI writers, DSP
// helpers, the Mixer, the reverb, the drum/melodic voice renderers,
// GenerateDrumClip/GenerateMelodicClip/Humanize). main() itself generates
// every code-authored song in one place, each in its own Generate*Song()
// function with its own dir/bpm/note tables - see Content/Byte Blaster (AI
// Slop)/Byte Blaster.chart, Content/Voltage Run (AI Slop)/Voltage Run.chart
// and Content/Quiet Hours/Quiet Hours.chart for the [song]/[clip]/section
// text each function was written to match (those files aren't generated by
// this tool - they're still hand-authored, same as any other chart).
// Keeping all three in one file, instead of overwriting main() per song
// like earlier versions of this file did, is deliberate: an earlier
// rewrite silently lost Voltage Run's original note tables (only the
// rendered .wav/.mid survived in git) - to author a new song without
// erasing the others, add a new Generate*Song() function and call it from
// main() alongside the rest, rather than replacing what's there.
//
// Mix/DSP notes (read this before tweaking levels): GenerateMelodicClip and
// GenerateDrumClip take a targetPeak that normalizes *that one clip* to a
// modest peak, not a hot near-0dBFS master - because a chart's sections
// regularly play several clips at once (see [background]/[break] in any
// .chart file), and this tool has no idea how many will stack on top of
// each other at runtime. Keep targetPeak in the ~0.3-0.6 range (matching
// the headroom real recorded stems in Content/ use - check with a peak/RMS
// tool before assuming a level is fine) rather than normalizing each clip
// toward 1.0 in isolation; the latter is exactly what made the original
// "AI Slop" songs clip and distort once multiple stems summed together.
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace
{

constexpr int c_SampleRate = 44100;
constexpr int c_TicksPerQuarter = 480;
constexpr int c_LaneMidiPitches[4] = {72, 74, 76, 77};

// ---------- WAV writer ----------

void WriteWavMono16(const std::string& path, const std::vector<int16_t>& samples)
{
    std::ofstream f(path, std::ios::binary);
    uint32_t dataBytes = static_cast<uint32_t>(samples.size() * sizeof(int16_t));
    uint32_t riffSize = 36 + dataBytes;
    uint16_t formatTag = 1; // PCM
    uint16_t channels = 1;
    uint32_t sampleRate = c_SampleRate;
    uint16_t bitsPerSample = 16;
    uint16_t blockAlign = channels * bitsPerSample / 8;
    uint32_t byteRate = sampleRate * blockAlign;
    uint32_t fmtSize = 16;

    f.write("RIFF", 4);
    f.write(reinterpret_cast<const char*>(&riffSize), 4);
    f.write("WAVE", 4);
    f.write("fmt ", 4);
    f.write(reinterpret_cast<const char*>(&fmtSize), 4);
    f.write(reinterpret_cast<const char*>(&formatTag), 2);
    f.write(reinterpret_cast<const char*>(&channels), 2);
    f.write(reinterpret_cast<const char*>(&sampleRate), 4);
    f.write(reinterpret_cast<const char*>(&byteRate), 4);
    f.write(reinterpret_cast<const char*>(&blockAlign), 2);
    f.write(reinterpret_cast<const char*>(&bitsPerSample), 2);
    f.write("data", 4);
    f.write(reinterpret_cast<const char*>(&dataBytes), 4);
    f.write(reinterpret_cast<const char*>(samples.data()), dataBytes);
}

// ---------- MIDI writer ----------

void WriteVLQ(std::vector<uint8_t>& out, uint32_t value)
{
    uint8_t buffer[4];
    int count = 0;
    buffer[count++] = static_cast<uint8_t>(value & 0x7F);
    value >>= 7;
    while (value > 0)
    {
        buffer[count++] = static_cast<uint8_t>(value & 0x7F);
        value >>= 7;
    }
    for (int i = count - 1; i >= 0; --i)
    {
        uint8_t b = buffer[i];
        if (i != 0)
        {
            b |= 0x80;
        }
        out.push_back(b);
    }
}

void WriteBE32(std::ofstream& f, uint32_t v)
{
    uint8_t b[4] = {static_cast<uint8_t>(v >> 24), static_cast<uint8_t>(v >> 16), static_cast<uint8_t>(v >> 8),
                     static_cast<uint8_t>(v)};
    f.write(reinterpret_cast<const char*>(b), 4);
}

void WriteBE16(std::ofstream& f, uint16_t v)
{
    uint8_t b[2] = {static_cast<uint8_t>(v >> 8), static_cast<uint8_t>(v)};
    f.write(reinterpret_cast<const char*>(b), 2);
}

struct MidiNote
{
    int startTick = 0;
    int endTick = 0;
    int pitch = 0;
};

void WriteMidiFile(const std::string& path, const std::vector<MidiNote>& notes, int totalTicks)
{
    struct RawEvent
    {
        int tick;
        bool isOn;
        int pitch;
    };
    std::vector<RawEvent> events;
    events.reserve(notes.size() * 2);
    for (const MidiNote& n : notes)
    {
        events.push_back({n.startTick, true, n.pitch});
        events.push_back({n.endTick, false, n.pitch});
    }
    std::stable_sort(events.begin(), events.end(),
                      [](const RawEvent& a, const RawEvent& b)
                      {
                          if (a.tick != b.tick)
                          {
                              return a.tick < b.tick;
                          }
                          // Note-offs before note-ons at the same tick, so a
                          // back-to-back same-pitch/lane repeat never reads
                          // as a zero-length overlap.
                          return !a.isOn && b.isOn;
                      });

    std::vector<uint8_t> track;
    int prevTick = 0;
    for (const RawEvent& e : events)
    {
        WriteVLQ(track, static_cast<uint32_t>(e.tick - prevTick));
        prevTick = e.tick;
        track.push_back(e.isOn ? 0x90 : 0x80);
        track.push_back(static_cast<uint8_t>(e.pitch));
        track.push_back(e.isOn ? 100 : 64);
    }
    // End-of-track meta event, placed at totalTicks (not just the last
    // note's own end) so the pattern's declared length matches the audio's
    // full loop instead of shrinking to whatever the last note happened to
    // end on.
    WriteVLQ(track, static_cast<uint32_t>(std::max(0, totalTicks - prevTick)));
    track.push_back(0xFF);
    track.push_back(0x2F);
    track.push_back(0x00);

    std::ofstream f(path, std::ios::binary);
    f.write("MThd", 4);
    WriteBE32(f, 6);
    WriteBE16(f, 0); // format 0: single track
    WriteBE16(f, 1); // ntrks
    WriteBE16(f, static_cast<uint16_t>(c_TicksPerQuarter));
    f.write("MTrk", 4);
    WriteBE32(f, static_cast<uint32_t>(track.size()));
    f.write(reinterpret_cast<const char*>(track.data()), static_cast<std::streamsize>(track.size()));
}

// ---------- DSP ----------

// Deterministic LCG noise so re-running the generator reproduces byte-
// identical output.
double NoiseSample(uint32_t& state)
{
    state = state * 1664525u + 1013904223u;
    return (static_cast<double>(state) / 4294967295.0) * 2.0 - 1.0;
}

double Square(double phase)
{
    return std::fmod(phase, 1.0) < 0.5 ? 1.0 : -1.0;
}

double Triangle(double phase)
{
    double p = std::fmod(phase, 1.0);
    return p < 0.5 ? (4.0 * p - 1.0) : (3.0 - 4.0 * p);
}

// One-pole low-pass; alpha in (0,1], smaller = darker.
double OnePoleLowPass(double x, double& state, double alpha)
{
    state += alpha * (x - state);
    return state;
}

// tanh soft-knee limiter: transparent below threshold, rounds off peaks
// above it instead of flat-topping them the way a hard clamp does - a
// safety net for the rare transient that pokes over targetPeak, not
// something the normal mix should lean on.
double SoftClip(double x, double threshold = 0.85)
{
    double sign = x < 0.0 ? -1.0 : 1.0;
    double a = std::abs(x);
    if (a <= threshold)
    {
        return x;
    }
    double over = (a - threshold) / (1.0 - threshold);
    double compressed = threshold + (1.0 - threshold) * std::tanh(over);
    return sign * compressed;
}

// ---------- Small Schroeder reverb (mono) ----------
//
// Four parallel feedback combs (each with a damped low-pass in its feedback
// path, so the tail darkens as it decays instead of ringing brightly
// forever) summed and run through two series allpasses to diffuse it into
// a smooth wash rather than discrete echoes. This is the single biggest
// lever for not sounding like a dry, close-mic'd synth demo - real
// recorded stems in Content/ all carry some room/plugin space; the
// original "AI Slop" clips had none at all.
struct CombFilter
{
    std::vector<double> buffer;
    size_t pos = 0;
    double feedback;
    double damp;
    double dampState = 0.0;

    CombFilter(int delaySamples, double feedbackAmt, double dampAmt)
        : buffer(static_cast<size_t>(delaySamples), 0.0), feedback(feedbackAmt), damp(dampAmt)
    {
    }

    double Process(double input)
    {
        double out = buffer[pos];
        dampState = OnePoleLowPass(out, dampState, 1.0 - damp);
        buffer[pos] = input + dampState * feedback;
        pos = (pos + 1) % buffer.size();
        return out;
    }
};

struct AllpassFilter
{
    std::vector<double> buffer;
    size_t pos = 0;
    double feedback;

    AllpassFilter(int delaySamples, double feedbackAmt) : buffer(static_cast<size_t>(delaySamples), 0.0), feedback(feedbackAmt)
    {
    }

    double Process(double input)
    {
        double bufOut = buffer[pos];
        double output = -input + bufOut;
        buffer[pos] = input + bufOut * feedback;
        pos = (pos + 1) % buffer.size();
        return output;
    }
};

// Runs `dry` through the reverb twice back-to-back and keeps only the
// second pass's output, so the tail has already settled into its loop-
// steady-state by the time playback actually starts - the returned buffer
// is exactly dry.size() samples (no trailing tail appended), which matters
// because every clip's duration is load-bearing: ChartClip's loop/advance
// math assumes a clip's audio length exactly matches its authored beat
// length, so we can't just bolt a decay tail onto the end.
std::vector<double> ApplyLoopingReverb(const std::vector<double>& dry, double wetSend, double roomSize)
{
    if (wetSend <= 0.0 || dry.empty())
    {
        return dry;
    }
    static const int c_CombTuningsSamples[4] = {1557, 1617, 1491, 1422};
    static const int c_AllpassTuningsSamples[2] = {556, 441};

    std::vector<CombFilter> combs;
    for (int t : c_CombTuningsSamples)
    {
        combs.emplace_back(t, 0.26 + roomSize * 0.32, 0.25);
    }
    std::vector<AllpassFilter> allpasses;
    for (int t : c_AllpassTuningsSamples)
    {
        allpasses.emplace_back(t, 0.5);
    }

    size_t n = dry.size();
    std::vector<double> wetSecondPass(n);
    for (int pass = 0; pass < 2; ++pass)
    {
        for (size_t i = 0; i < n; ++i)
        {
            double input = dry[i];
            double sum = 0.0;
            for (CombFilter& c : combs)
            {
                sum += c.Process(input);
            }
            sum *= 0.25;
            for (AllpassFilter& a : allpasses)
            {
                sum = a.Process(sum);
            }
            if (pass == 1)
            {
                wetSecondPass[i] = sum;
            }
        }
    }
    std::vector<double> out(n);
    for (size_t i = 0; i < n; ++i)
    {
        out[i] = dry[i] + wetSecondPass[i] * wetSend;
    }
    return out;
}

struct Mixer
{
    std::vector<double> buffer; // -1..1 range, additive

    explicit Mixer(int totalSamples) : buffer(static_cast<size_t>(totalSamples), 0.0)
    {
    }

    void Add(int startSample, const std::vector<double>& voice)
    {
        for (size_t i = 0; i < voice.size(); ++i)
        {
            size_t idx = static_cast<size_t>(startSample) + i;
            if (idx < buffer.size())
            {
                buffer[idx] += voice[i];
            }
        }
    }

    // wetSend 0 disables the reverb entirely (cheap no-op) - see
    // ApplyLoopingReverb's own comment for why this preserves buffer length.
    void ApplyInsertReverb(double wetSend, double roomSize)
    {
        buffer = ApplyLoopingReverb(buffer, wetSend, roomSize);
    }

    // targetPeak should be a headroom-aware level (~0.3-0.6), not close to
    // 1.0 - see this file's top comment. SoftClip is just a safety net for
    // whatever narrow transient still pokes past it.
    std::vector<int16_t> ToPcm16(double targetPeak) const
    {
        double peak = 1e-6;
        for (double v : buffer)
        {
            peak = std::max(peak, std::abs(v));
        }
        double scale = peak > targetPeak ? (targetPeak / peak) : 1.0;
        std::vector<int16_t> out(buffer.size());
        for (size_t i = 0; i < buffer.size(); ++i)
        {
            double v = SoftClip(buffer[i] * scale);
            out[i] = static_cast<int16_t>(std::lround(std::clamp(v, -1.0, 1.0) * 32767.0));
        }
        return out;
    }
};

// ---------- Instrument voices ----------

// Percussive drum hit rendered straight into a fresh vector, added into the
// mixer at the event's own start sample - envelope length is the drum's own
// natural decay, independent of however short the chart's own tap-note
// duration is (a real drum's sound outlasts a quick press/release gesture).
std::vector<double> RenderKick(uint32_t& noiseState)
{
    int n = static_cast<int>(0.20 * c_SampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(c_SampleRate);
        double freq = 150.0 * std::exp(-t * 28.0) + 48.0; // pitch sweep, high -> low
        double phase = std::fmod(t * freq, 1.0);
        double tone = std::sin(2.0 * 3.14159265358979 * phase);
        double amp = std::exp(-t * 16.0);
        // Softer, shorter click than before (was 0.35 over 4ms) - the
        // original read as a harsh digital tick sitting on top of the kick.
        double click = (t < 0.003) ? NoiseSample(noiseState) * (1.0 - t / 0.003) * 0.18 : 0.0;
        v[static_cast<size_t>(i)] = (tone * amp + click) * 0.9;
    }
    return v;
}

std::vector<double> RenderSnare(uint32_t& noiseState)
{
    int n = static_cast<int>(0.16 * c_SampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    double lpState = 0.0;
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(c_SampleRate);
        double noise = NoiseSample(noiseState);
        lpState = OnePoleLowPass(noise, lpState, 0.5);
        double highPassed = noise - lpState; // crude high-pass: original minus a low-passed copy
        double noiseAmp = std::exp(-t * 24.0);
        double tone = std::sin(2.0 * 3.14159265358979 * 190.0 * t) * std::exp(-t * 30.0);
        v[static_cast<size_t>(i)] = (highPassed * 0.6 * noiseAmp + tone * 0.5) * 0.8;
    }
    return v;
}

std::vector<double> RenderHihat(uint32_t& noiseState)
{
    int n = static_cast<int>(0.06 * c_SampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    double lp1 = 0.0, lp2 = 0.0, lp3 = 0.0;
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(c_SampleRate);
        double noise = NoiseSample(noiseState);
        lp1 = OnePoleLowPass(noise, lp1, 0.35);
        lp2 = OnePoleLowPass(lp1, lp2, 0.35);
        // A third cascaded LP (was two) rounds off the harshest top end a
        // touch more while still leaving plenty of sizzle.
        lp3 = OnePoleLowPass(lp2, lp3, 0.45);
        double highPassed = noise - lp3;
        double amp = std::exp(-t * 55.0);
        v[static_cast<size_t>(i)] = highPassed * amp * 0.5;
    }
    return v;
}

std::vector<double> RenderTom(uint32_t& noiseState)
{
    int n = static_cast<int>(0.18 * c_SampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(c_SampleRate);
        double freq = 300.0 * std::exp(-t * 14.0) + 130.0;
        double phase = std::fmod(t * freq, 1.0);
        double tone = std::sin(2.0 * 3.14159265358979 * phase);
        double amp = std::exp(-t * 13.0);
        double noise = NoiseSample(noiseState) * 0.08 * std::exp(-t * 40.0);
        v[static_cast<size_t>(i)] = (tone * amp + noise) * 0.85;
    }
    return v;
}

enum class Timbre
{
    Square,
    Triangle,
    Bell,
    // A soft sub-register voice for a bassline: triangle+sine blend (far
    // fewer/weaker harmonics than Square - see RenderMelodicNote), then
    // run through an extra low-pass pass of its own on top of the shared
    // envelope, so it reads as warm low end instead of competing with the
    // lead/arp's own brighter timbres up in the mix.
    Bass,
};

// Melodic note - length follows the chart's own note duration (in
// seconds), giving a short envelope with a bit of release tail so back-to-
// back staccato notes never click. velocity is a linear gain multiplier
// (1.0 = full), used to humanize a performance instead of every note
// hitting identically.
std::vector<double> RenderMelodicNote(double freqHz, double durationSeconds, Timbre timbre, double velocity = 1.0)
{
    double releaseSeconds = (timbre == Timbre::Bell) ? 0.45 : 0.10;
    int n = static_cast<int>((durationSeconds + releaseSeconds) * c_SampleRate);
    n = std::max(n, 8);
    std::vector<double> v(static_cast<size_t>(n));
    double attackSeconds = (timbre == Timbre::Bell) ? 0.015 : 0.006;
    // Sustain plateau well below the old flat 0.85 - at 0.85 a held square/
    // triangle note reads as a constant wall of buzz (crest factor ~1.9,
    // i.e. almost no dynamic shape at all). Bell keeps its own decaying
    // sustain curve below.
    double sustainLevel = (timbre == Timbre::Bell) ? 1.0 : 0.55;
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(c_SampleRate);
        double env;
        if (t < attackSeconds)
        {
            env = (t / attackSeconds) * sustainLevel;
        }
        else if (t < durationSeconds)
        {
            env = (timbre == Timbre::Bell) ? std::exp(-(t - attackSeconds) * 1.2) : sustainLevel;
        }
        else
        {
            double releaseT = t - durationSeconds;
            double heldLevel =
                (timbre == Timbre::Bell) ? std::exp(-(durationSeconds - attackSeconds) * 1.2) : sustainLevel;
            env = heldLevel * std::exp(-releaseT / (releaseSeconds * 0.35));
        }

        double sample = 0.0;
        if (timbre == Timbre::Square)
        {
            sample = Square(t * freqHz) * 0.5;
        }
        else if (timbre == Timbre::Triangle)
        {
            sample = Triangle(t * freqHz) * 0.6;
        }
        else if (timbre == Timbre::Bass)
        {
            sample = (Triangle(t * freqHz) * 0.6 + std::sin(2.0 * 3.14159265358979 * freqHz * t) * 0.4) * 0.6;
        }
        else // Bell
        {
            sample = std::sin(2.0 * 3.14159265358979 * freqHz * t) * 0.5 +
                     std::sin(2.0 * 3.14159265358979 * freqHz * 2.01 * t) * 0.18 +
                     std::sin(2.0 * 3.14159265358979 * freqHz * 3.0 * t) * 0.08;
        }
        v[static_cast<size_t>(i)] = sample * env * velocity;
    }

    if (timbre == Timbre::Square || timbre == Timbre::Triangle)
    {
        // Rounds off the raw oscillator's harshest upper harmonics -
        // Square gets more smoothing than Triangle since it starts with
        // far more high-harmonic content to begin with.
        double state = 0.0;
        double alpha = (timbre == Timbre::Square) ? 0.5 : 0.75;
        for (double& s : v)
        {
            s = OnePoleLowPass(s, state, alpha);
        }
    }
    else if (timbre == Timbre::Bass)
    {
        // A second low-pass pass smooths off whatever edge the
        // triangle+sine blend still has, so it reads as round low end
        // rather than a synth tone that merely happens to be pitched low.
        double state = 0.0;
        for (double& s : v)
        {
            s = OnePoleLowPass(s, state, 0.18);
        }
    }
    return v;
}

// ---------- Clip data model ----------

enum class DrumPart
{
    Kick,
    Snare,
    Hihat,
    Tom,
};

struct DrumHit
{
    double beat;
    int lane; // also selects the part: 0=kick,1=snare,2=hihat,3=tom
    double velocity = 1.0;
};

struct MelodicEvent
{
    double beat;
    double durationBeats;
    int lane;
    double freqHz;
    double velocity = 1.0;
};

// Nudges each event's timing/velocity by a small deterministic amount so a
// programmed pattern doesn't read as perfectly typed-in - real playing
// never lands two notes with identical timing and force. Only ever applied
// to the "audio" event lists, never to chartEvents/chartHits: the judged
// note chart has to stay exactly quantized to what ChartMidi loads, since
// that's what the player is being timed against.
std::vector<MelodicEvent> Humanize(std::vector<MelodicEvent> events, uint32_t seed, double timingJitterBeats,
                                    double velocityJitter)
{
    uint32_t state = seed;
    for (MelodicEvent& e : events)
    {
        e.beat = std::max(0.0, e.beat + NoiseSample(state) * timingJitterBeats);
        e.velocity *= 1.0 + NoiseSample(state) * velocityJitter;
    }
    return events;
}

std::vector<DrumHit> HumanizeDrums(std::vector<DrumHit> hits, uint32_t seed, double timingJitterBeats,
                                    double velocityJitter)
{
    uint32_t state = seed;
    for (DrumHit& h : hits)
    {
        h.beat = std::max(0.0, h.beat + NoiseSample(state) * timingJitterBeats);
        h.velocity *= 1.0 + NoiseSample(state) * velocityJitter;
    }
    return hits;
}

// Renders a drum-pattern clip's audio from audioHits (the "real"
// performance - as busy/musical as sounds good) and, unless
// chartHits is empty, a SEPARATE note chart from chartHits - deliberately
// not the same list. The audio is what the arrangement actually needs to
// sound good; the chart is what the player actually needs to judge, and
// the two don't have to agree on density at all (see GenerateMelodicClip's
// own comment for why this split exists).
//
// targetPeak/reverbSend/roomSize: see this file's top comment on gain
// staging - keep targetPeak well under 1.0 so simultaneous clips (see any
// [background]/[break] section) sum without clipping.
void GenerateDrumClip(const std::string& dir, const std::string& name, const std::vector<DrumHit>& audioHits,
                       const std::vector<DrumHit>& chartHits, double totalBeats, double secondsPerBeat,
                       uint32_t noiseSeed, double targetPeak = 0.55, double reverbSend = 0.0, double roomSize = 0.3)
{
    int totalSamples = static_cast<int>(std::lround(totalBeats * secondsPerBeat * c_SampleRate));
    Mixer mixer(totalSamples);
    uint32_t noiseState = noiseSeed;

    for (const DrumHit& h : audioHits)
    {
        int startSample = static_cast<int>(std::lround(h.beat * secondsPerBeat * c_SampleRate));
        std::vector<double> voice;
        switch (h.lane)
        {
            case 0:
                voice = RenderKick(noiseState);
                break;
            case 1:
                voice = RenderSnare(noiseState);
                break;
            case 2:
                voice = RenderHihat(noiseState);
                break;
            default:
                voice = RenderTom(noiseState);
                break;
        }
        for (double& s : voice)
        {
            s *= h.velocity;
        }
        mixer.Add(startSample, voice);
    }
    mixer.ApplyInsertReverb(reverbSend, roomSize);
    WriteWavMono16(dir + "/" + name + ".wav", mixer.ToPcm16(targetPeak));

    if (!chartHits.empty())
    {
        std::vector<MidiNote> notes;
        for (const DrumHit& h : chartHits)
        {
            int startTick = static_cast<int>(std::lround(h.beat * c_TicksPerQuarter));
            int endTick = startTick + static_cast<int>(std::lround(0.15 * c_TicksPerQuarter));
            notes.push_back({startTick, endTick, c_LaneMidiPitches[h.lane]});
        }
        int totalTicks = static_cast<int>(std::lround(totalBeats * c_TicksPerQuarter));
        WriteMidiFile(dir + "/" + name + ".mid", notes, totalTicks);
        printf("  %s: %d audio hits / %d chart hits, %.2fs, %d ticks\n", name.c_str(), (int)audioHits.size(),
               (int)chartHits.size(), totalBeats * secondsPerBeat, totalTicks);
    }
    else
    {
        printf("  %s: %d audio hits (background, no chart), %.2fs\n", name.c_str(), (int)audioHits.size(),
               totalBeats * secondsPerBeat);
    }
}

// audioEvents drives the actual musical arrangement (the WAV) - as dense
// or intricate as sounds good, e.g. a fast 16th-note arpeggio. chartEvents
// drives the judged note chart, authored independently and typically much
// sparser: a section's clip is picked, at BeginSection, purely by index
// into ChartSong::clips/laneNotes (see GameSession.h) - it never inspects
// the audio at all - so nothing requires the two to have matching density.
// Keeping the chart easy while the audio stays full-arrangement is exactly
// the intended use of that decoupling.
void GenerateMelodicClip(const std::string& dir, const std::string& name, const std::vector<MelodicEvent>& audioEvents,
                          const std::vector<MelodicEvent>& chartEvents, double totalBeats, double secondsPerBeat,
                          Timbre timbre, double targetPeak = 0.42, double reverbSend = 0.12, double roomSize = 0.35)
{
    int totalSamples = static_cast<int>(std::lround(totalBeats * secondsPerBeat * c_SampleRate));
    Mixer mixer(totalSamples);
    for (const MelodicEvent& e : audioEvents)
    {
        int startSample = static_cast<int>(std::lround(e.beat * secondsPerBeat * c_SampleRate));
        std::vector<double> voice = RenderMelodicNote(e.freqHz, e.durationBeats * secondsPerBeat, timbre, e.velocity);
        mixer.Add(startSample, voice);
    }
    mixer.ApplyInsertReverb(reverbSend, roomSize);
    WriteWavMono16(dir + "/" + name + ".wav", mixer.ToPcm16(targetPeak));

    std::vector<MidiNote> notes;
    for (const MelodicEvent& e : chartEvents)
    {
        int startTick = static_cast<int>(std::lround(e.beat * c_TicksPerQuarter));
        int endTick = static_cast<int>(std::lround((e.beat + e.durationBeats) * c_TicksPerQuarter));
        notes.push_back({startTick, endTick, c_LaneMidiPitches[e.lane]});
    }
    int totalTicks = static_cast<int>(std::lround(totalBeats * c_TicksPerQuarter));
    WriteMidiFile(dir + "/" + name + ".mid", notes, totalTicks);
    printf("  %s: %d audio notes / %d chart notes, %.2fs, %d ticks\n", name.c_str(), (int)audioEvents.size(),
           (int)chartEvents.size(), totalBeats * secondsPerBeat, totalTicks);
}

// ---------- Note-name frequency helpers (A4 = 440Hz equal temperament) ----------
constexpr double c_G1 = 48.999, c_B1 = 61.735;
constexpr double c_C2 = 65.406, c_D2 = 73.416, c_E2 = 82.407, c_Fs2 = 92.499, c_G2 = 97.999, c_A2 = 110.000,
                  c_B2 = 123.471, c_C3 = 130.813, c_D3 = 146.832, c_E3 = 164.814, c_F3 = 174.614, c_G3 = 195.998,
                  c_A3 = 220.000, c_B3 = 246.942;
constexpr double c_C4 = 261.626, c_D4 = 293.665, c_E4 = 329.628, c_F4 = 349.228, c_G4 = 391.995, c_A4 = 440.000,
                  c_B4 = 493.883;
constexpr double c_C5 = 523.251, c_D5 = 587.330, c_E5 = 659.255, c_F5 = 698.456, c_G5 = 783.991, c_A5 = 880.000;

} // namespace

// ================================================================
// Byte Blaster (AI Slop) - Content/Byte Blaster (AI Slop)/Byte Blaster.chart
// ================================================================
void GenerateByteBlaster()
{
    std::string dir = "Content/Byte Blaster (AI Slop)";
    const double bpm = 150.0;
    const double secondsPerBeat = 60.0 / bpm;
    printf("=== Byte Blaster (AI Slop) ===\n");

    // --- drum_intro: full musical fill for audio, a plain on/off-beat
    // alternation for the chart - the easiest possible pattern, fitting
    // for the song's own tutorial/first section.
    printf("Generating drum_intro...\n");
    std::vector<DrumHit> drumIntroAudio{
        {0.00, 0}, {1.00, 0}, {1.50, 2}, {2.00, 1}, {3.00, 0}, {3.50, 2},
        {4.00, 0}, {4.50, 0}, {5.00, 1}, {5.50, 2}, {6.00, 0}, {6.50, 2},
        {7.00, 1}, {7.25, 3}, {7.50, 3}, {7.75, 0},
    };
    GenerateDrumClip(dir, "drum_intro", HumanizeDrums(drumIntroAudio, 9001u, 0.01, 0.12),
                      {
                          {0.00, 0}, {1.00, 1}, {2.00, 0}, {3.00, 1}, {4.00, 0}, {5.00, 1}, {6.00, 0}, {7.00, 1},
                      },
                      8.0, secondsPerBeat, 1001u, 0.55, 0.05, 0.25);

    printf("Generating drums (background only, no chart)...\n");
    std::vector<DrumHit> drumsAudio{
        {0.00, 0}, {0.50, 2}, {1.00, 1}, {1.50, 2}, {2.00, 0}, {2.50, 2}, {3.00, 1}, {3.50, 2},
        {4.00, 0}, {4.50, 2}, {5.00, 1}, {5.50, 2}, {6.00, 0}, {6.50, 2}, {7.00, 1}, {7.25, 3},
        {7.50, 3}, {7.75, 3},
    };
    GenerateDrumClip(dir, "drums", HumanizeDrums(drumsAudio, 9002u, 0.01, 0.12), {}, 8.0, secondsPerBeat, 2002u, 0.55,
                      0.05, 0.25);

    // drums_2 chart: a simple 4-lane rotation with one syncopated moment -
    // busier-feeling than drum_intro's chart without actually being hard.
    printf("Generating drums_2...\n");
    std::vector<DrumHit> drums2Audio{
        {0.00, 0}, {0.75, 0}, {1.00, 1}, {1.50, 2}, {2.00, 0}, {2.25, 0}, {2.75, 2}, {3.00, 1},
        {3.50, 2}, {3.75, 0}, {4.00, 0}, {4.50, 2}, {5.00, 1}, {5.25, 3}, {5.50, 2}, {6.00, 0},
        {6.50, 0}, {6.75, 2}, {7.00, 1}, {7.25, 3}, {7.50, 3}, {7.75, 0},
    };
    GenerateDrumClip(dir, "drums_2", HumanizeDrums(drums2Audio, 9003u, 0.01, 0.12),
                      {
                          {0.00, 0}, {1.00, 1}, {2.00, 2}, {3.00, 3}, {4.00, 0}, {4.50, 0}, {5.00, 1}, {6.00, 2},
                          {7.00, 3}, {7.50, 0},
                      },
                      8.0, secondsPerBeat, 3003u, 0.55, 0.05, 0.25);

    // Bass: audio keeps the full moving line on the soft Bass timbre so it
    // sits underneath instead of buzzing in the same register as
    // everything else. Chart is a plain once-per-beat pulse, easy to lock
    // into.
    printf("Generating bass...\n");
    std::vector<MelodicEvent> bassAudio{
        {0.00, 0.40, 0, c_C2}, {0.75, 0.40, 0, c_C2}, {1.50, 0.40, 1, c_G1}, {2.00, 0.40, 0, c_C2},
        {2.75, 0.40, 2, c_E2}, {3.50, 0.40, 0, c_C2}, {4.00, 0.40, 2, c_G1}, {4.75, 0.40, 2, c_G1},
        {5.50, 0.40, 3, c_D2}, {6.00, 0.40, 2, c_G1}, {6.75, 0.40, 1, c_B1}, {7.50, 0.40, 2, c_G1},
    };
    GenerateMelodicClip(dir, "bass", Humanize(bassAudio, 9010u, 0.008, 0.08),
                         {
                             {0.00, 0.6, 0, c_C2}, {1.00, 0.6, 1, c_G1}, {2.00, 0.6, 0, c_C2}, {3.00, 0.6, 2, c_E2},
                             {4.00, 0.6, 0, c_G1}, {5.00, 0.6, 1, c_D2}, {6.00, 0.6, 0, c_G1}, {7.00, 0.6, 3, c_B1},
                         },
                         8.0, secondsPerBeat, Timbre::Bass, 0.42, 0.0, 0.3);

    // Arp: audio stays the full fast 16th-note run (that's what makes it
    // sound like an arpeggio) - the chart instead asks for just one press
    // per beat, cycling through all four lanes, so the player never has to
    // actually keep up with the 16ths.
    printf("Generating arp...\n");
    {
        std::vector<MelodicEvent> arpAudio;
        double cChord[4] = {c_C4, c_E4, c_G4, c_C5};
        double gChord[4] = {c_G4, c_B4, c_D5, c_C5 * (783.991 / 523.251)}; // G4,B4,D5,G5
        for (int bar = 0; bar < 2; ++bar)
        {
            const double* chord = (bar == 0) ? cChord : gChord;
            for (int step = 0; step < 16; ++step)
            {
                double beat = bar * 4.0 + step * 0.25;
                int lane = step % 4;
                arpAudio.push_back({beat, 0.18, lane, chord[lane]});
            }
        }
        std::vector<MelodicEvent> arpChart;
        for (int beat = 0; beat < 8; ++beat)
        {
            const double* chord = (beat < 4) ? cChord : gChord;
            int lane = beat % 4;
            arpChart.push_back({static_cast<double>(beat), 0.5, lane, chord[lane]});
        }
        GenerateMelodicClip(dir, "arp", Humanize(arpAudio, 9011u, 0.006, 0.1), arpChart, 8.0, secondsPerBeat,
                             Timbre::Triangle, 0.4, 0.1, 0.3);
    }

    // Lead: audio keeps the full melodic phrase; chart keeps only its
    // strongest/most memorable notes (the two held hook landings plus a
    // handful of on-the-beat pickups), evenly spaced and easy to follow.
    printf("Generating lead...\n");
    std::vector<MelodicEvent> leadAudio{
        {0.00, 0.5, 0, c_E4}, {0.50, 0.5, 1, c_G4}, {1.00, 0.5, 2, c_A4}, {1.50, 0.5, 1, c_G4},
        {2.00, 1.0, 3, c_C5}, {3.00, 0.75, 2, c_B4}, {3.75, 0.25, 2, c_A4}, {4.00, 0.5, 1, c_G4},
        {4.50, 0.5, 0, c_E4}, {5.00, 0.5, 0, c_D4}, {5.50, 0.5, 0, c_E4}, {6.00, 1.0, 1, c_G4},
        {7.00, 0.5, 1, c_F4}, {7.50, 0.5, 0, c_E4},
    };
    GenerateMelodicClip(dir, "lead", Humanize(leadAudio, 9012u, 0.008, 0.1),
                         {
                             {0.00, 0.8, 0, c_E4}, {1.00, 0.8, 1, c_G4}, {2.00, 1.5, 3, c_C5}, {3.50, 0.4, 2, c_B4},
                             {4.00, 0.8, 1, c_G4}, {5.00, 0.8, 0, c_E4}, {6.00, 1.5, 1, c_G4}, {7.50, 0.4, 0, c_E4},
                         },
                         8.0, secondsPerBeat, Timbre::Square, 0.42, 0.12, 0.3);

    printf("Generating lead_2...\n");
    std::vector<MelodicEvent> lead2Audio{
        {0.00, 0.5, 2, c_A4}, {0.50, 0.5, 3, c_C5}, {1.00, 0.5, 3, c_E5}, {1.50, 0.5, 3, c_C5},
        {2.00, 1.0, 2, c_A4}, {3.00, 0.5, 1, c_G4}, {3.50, 0.5, 2, c_A4}, {4.00, 0.5, 0, c_F4},
        {4.50, 0.5, 2, c_A4}, {5.00, 0.5, 3, c_C5}, {5.50, 0.5, 2, c_A4}, {6.00, 1.0, 0, c_F4},
        {7.00, 0.5, 1, c_G4}, {7.50, 0.5, 2, c_A4},
    };
    GenerateMelodicClip(dir, "lead_2", Humanize(lead2Audio, 9013u, 0.008, 0.1),
                         {
                             {0.00, 0.8, 2, c_A4}, {1.00, 0.8, 3, c_C5}, {2.00, 1.5, 2, c_A4}, {3.50, 0.4, 1, c_G4},
                             {4.00, 0.8, 0, c_F4}, {5.00, 0.8, 2, c_A4}, {6.00, 1.5, 0, c_F4}, {7.50, 0.4, 1, c_G4},
                         },
                         8.0, secondsPerBeat, Timbre::Square, 0.42, 0.12, 0.3);

    // Bell Bridge is already sparse and DontFail (forgiving) - chart
    // matches the audio unchanged, no simplification needed.
    printf("Generating bell_bridge (DontFail)...\n");
    std::vector<MelodicEvent> bellEvents{
        {0.00, 0.8, 2, c_A4}, {1.00, 0.8, 3, c_C5}, {2.00, 1.8, 3, c_E5},
        {4.00, 0.8, 1, c_F4}, {5.00, 0.8, 2, c_A4}, {6.00, 1.8, 3, c_C5},
        {8.00, 0.8, 0, c_C4}, {9.00, 0.8, 1, c_E4}, {10.00, 1.8, 1, c_G4},
        {12.00, 0.8, 1, c_G4}, {13.00, 0.8, 2, c_B4}, {14.00, 1.8, 3, c_D5},
    };
    GenerateMelodicClip(dir, "bell_bridge", Humanize(bellEvents, 9014u, 0.01, 0.08), bellEvents, 16.0, secondsPerBeat,
                         Timbre::Bell, 0.32, 0.22, 0.5);
}

// ================================================================
// Voltage Run (AI Slop) - Content/Voltage Run (AI Slop)/Voltage Run.chart
//
// Chart-note timings below were recovered from the .mid files already
// committed to the repo (this song's original generator code was lost -
// see this file's top comment for why every song now lives here instead)
// by dumping their note on/off events; they're reproduced exactly so the
// judged difficulty the chart's hits_required values were tuned against
// doesn't change. Only the audio arrangement and all DSP/mix are new.
// ================================================================
void GenerateVoltageRun()
{
    std::string dir = "Content/Voltage Run (AI Slop)";
    const double bpm = 128.0;
    const double secondsPerBeat = 60.0 / bpm;
    printf("=== Voltage Run (AI Slop) ===\n");

    // drum_intro: 4-beat plain alternation chart (kick/snare/kick/hihat),
    // audio gets a fuller fill around it.
    printf("Generating drum_intro...\n");
    std::vector<DrumHit> drumIntroChart{
        {0.00, 0}, {1.00, 1}, {2.00, 0}, {3.00, 2},
    };
    std::vector<DrumHit> drumIntroAudio{
        {0.00, 0}, {0.50, 2}, {1.00, 1}, {1.50, 2}, {2.00, 0}, {2.50, 2}, {3.00, 2}, {3.50, 3},
    };
    GenerateDrumClip(dir, "drum_intro", HumanizeDrums(drumIntroAudio, 8101u, 0.01, 0.12), drumIntroChart, 4.0,
                      secondsPerBeat, 4001u, 0.55, 0.05, 0.25);

    // drums: plays only in [background] sections (never judged), but the
    // original still carried a plain quarter-note chart pattern - recovered
    // from drums.mid and reproduced here rather than silently dropped.
    printf("Generating drums...\n");
    std::vector<DrumHit> drumsChart;
    for (int bar = 0; bar < 4; ++bar)
    {
        double base = bar * 4.0;
        drumsChart.push_back({base + 0.0, 0});
        drumsChart.push_back({base + 1.0, 2});
        drumsChart.push_back({base + 2.0, 1});
        drumsChart.push_back({base + 3.0, 2});
    }
    std::vector<DrumHit> drumsAudio;
    for (int bar = 0; bar < 4; ++bar)
    {
        double base = bar * 4.0;
        drumsAudio.push_back({base + 0.0, 0});
        drumsAudio.push_back({base + 0.5, 2});
        drumsAudio.push_back({base + 1.0, 1});
        drumsAudio.push_back({base + 1.5, 2});
        drumsAudio.push_back({base + 2.0, 0});
        drumsAudio.push_back({base + 2.5, 2});
        drumsAudio.push_back({base + 3.0, 1});
        drumsAudio.push_back({base + 3.5, 2});
    }
    GenerateDrumClip(dir, "drums", HumanizeDrums(drumsAudio, 8102u, 0.01, 0.12), drumsChart, 16.0, secondsPerBeat,
                      4002u, 0.55, 0.05, 0.25);

    // drums_2 chart: recovered 8th-note pattern, kick/hihat/snare/hihat
    // repeating with a tom accent every other bar.
    printf("Generating drums_2...\n");
    std::vector<DrumHit> drums2Chart;
    for (int bar = 0; bar < 4; ++bar)
    {
        double base = bar * 4.0;
        drums2Chart.push_back({base + 0.0, 0});
        drums2Chart.push_back({base + 0.5, 2});
        drums2Chart.push_back({base + 1.0, 1});
        drums2Chart.push_back({base + 1.5, 2});
        drums2Chart.push_back({base + 2.0, 0});
        drums2Chart.push_back({base + 2.5, 2});
        drums2Chart.push_back({base + 3.0, 1});
        drums2Chart.push_back({base + 3.5, 3});
    }
    std::vector<DrumHit> drums2Audio = drums2Chart;
    drums2Audio.push_back({15.75, 2});
    GenerateDrumClip(dir, "drums_2", HumanizeDrums(drums2Audio, 8103u, 0.01, 0.12), drums2Chart, 16.0, secondsPerBeat,
                      4003u, 0.55, 0.05, 0.25);

    // Bass: recovered chart pulse, audio adds octave color and a touch of
    // syncopation to feel like a real driving bassline underneath.
    printf("Generating bass...\n");
    std::vector<MelodicEvent> bassChart{
        {0.00, 0.4, 0, c_C3}, {1.00, 0.4, 0, c_C3}, {2.00, 0.4, 1, c_D3}, {3.00, 0.4, 0, c_C3},
        {4.00, 0.4, 0, c_C3}, {5.00, 0.4, 0, c_C3}, {6.00, 0.4, 1, c_D3}, {7.00, 0.4, 2, c_E3},
        {8.00, 0.4, 0, c_C3}, {9.00, 0.4, 0, c_C3}, {10.00, 0.4, 1, c_D3}, {11.00, 0.4, 0, c_C3},
        {12.00, 0.4, 0, c_C3}, {13.00, 0.4, 2, c_E3}, {14.00, 0.4, 1, c_D3}, {15.00, 0.4, 3, c_Fs2},
    };
    std::vector<MelodicEvent> bassAudio;
    for (const MelodicEvent& e : bassChart)
    {
        bassAudio.push_back({e.beat, 0.35, e.lane, e.freqHz});
        bassAudio.push_back({e.beat + 0.5, 0.35, e.lane, e.freqHz});
    }
    GenerateMelodicClip(dir, "bass", Humanize(bassAudio, 8110u, 0.008, 0.08), bassChart, 16.0, secondsPerBeat,
                         Timbre::Bass, 0.42, 0.0, 0.3);

    // Arp: recovered quarter-note chart (one press per beat cycling all
    // four lanes); audio turns it into an actual 8th-note arpeggio run.
    printf("Generating arp...\n");
    {
        std::vector<MelodicEvent> arpChart{
            {0.00, 0.4, 0, c_C4}, {1.00, 0.4, 1, c_D4}, {2.00, 0.4, 2, c_E4}, {3.00, 0.4, 3, c_F4},
            {4.00, 0.4, 0, c_C4}, {5.00, 0.4, 1, c_D4}, {6.00, 0.4, 2, c_E4}, {7.00, 0.4, 3, c_F4},
            {8.00, 0.4, 0, c_C4}, {9.00, 0.4, 1, c_D4}, {10.00, 0.4, 2, c_E4}, {11.00, 0.4, 3, c_F4},
            {12.00, 0.4, 0, c_C4}, {13.00, 0.4, 1, c_D4}, {14.00, 0.4, 2, c_E4}, {15.00, 0.4, 3, c_F4},
        };
        std::vector<MelodicEvent> arpAudio;
        double chord[4] = {c_C4, c_D4, c_E4, c_F4};
        for (int beat = 0; beat < 16; ++beat)
        {
            for (int step = 0; step < 2; ++step)
            {
                int lane = (beat + step) % 4;
                arpAudio.push_back({beat + step * 0.5, 0.28, lane, chord[lane]});
            }
        }
        GenerateMelodicClip(dir, "arp", Humanize(arpAudio, 8111u, 0.006, 0.1), arpChart, 16.0, secondsPerBeat,
                             Timbre::Triangle, 0.4, 0.1, 0.3);
    }

    // Lead: recovered chart timings/pitches; audio fills in a bit of
    // pickup motion around each held chart note instead of dead silence.
    printf("Generating lead...\n");
    std::vector<MelodicEvent> leadChart{
        {0.00, 0.7, 0, c_C4}, {1.50, 0.7, 2, c_E4}, {3.00, 0.7, 1, c_D4}, {4.00, 0.7, 3, c_F4},
        {6.00, 0.7, 0, c_C4}, {8.00, 0.7, 2, c_E4}, {10.00, 0.7, 1, c_D4}, {13.00, 0.7, 0, c_C4},
    };
    std::vector<MelodicEvent> leadAudio = leadChart;
    leadAudio.push_back({5.50, 0.4, 1, c_D4});
    leadAudio.push_back({9.50, 0.4, 3, c_F4});
    leadAudio.push_back({12.00, 0.4, 2, c_E4});
    GenerateMelodicClip(dir, "lead", Humanize(leadAudio, 8112u, 0.008, 0.1), leadChart, 16.0, secondsPerBeat,
                         Timbre::Square, 0.42, 0.12, 0.3);

    // Lead 2: recovered chart timings/pitches; same light audio fill-in
    // treatment as lead.
    printf("Generating lead_2...\n");
    std::vector<MelodicEvent> lead2Chart{
        {0.00, 0.6, 2, c_E4}, {1.00, 0.6, 1, c_D4}, {2.50, 0.6, 3, c_F4}, {4.00, 0.6, 2, c_E4},
        {5.50, 0.6, 1, c_D4}, {7.00, 0.6, 0, c_C4}, {9.00, 0.6, 3, c_F4}, {11.00, 0.6, 2, c_E4},
        {12.00, 0.6, 1, c_D4}, {13.50, 0.6, 0, c_C4},
    };
    std::vector<MelodicEvent> lead2Audio = lead2Chart;
    lead2Audio.push_back({3.50, 0.35, 2, c_E4});
    lead2Audio.push_back({8.00, 0.35, 1, c_D4});
    lead2Audio.push_back({10.00, 0.35, 3, c_F4});
    GenerateMelodicClip(dir, "lead_2", Humanize(lead2Audio, 8113u, 0.008, 0.1), lead2Chart, 16.0, secondsPerBeat,
                         Timbre::Square, 0.42, 0.12, 0.3);
}

// ================================================================
// Quiet Hours - a brand new, deliberately calm song: slower tempo, no
// Square-timbre leads (the harshest/most "chiptune slop" sounding voice),
// soft brushed drums, longer/breathing note durations with real rests
// between phrases, and a heavier reverb send throughout for a warm, roomy
// feel instead of a dry synth demo. Key of A minor / C major (all diatonic
// - no jarring accidentals), mostly stepwise melodic motion.
// See Content/Quiet Hours/Quiet Hours.chart for the section layout this
// was written to match.
// ================================================================
void GenerateQuietHours()
{
    std::string dir = "Content/Quiet Hours";
    const double bpm = 84.0;
    const double secondsPerBeat = 60.0 / bpm;
    printf("=== Quiet Hours ===\n");

    // drum_intro: soft brushed kick/hihat pulse, half-time feel - the
    // easiest possible pattern (kick/hihat alternation) for the song's own
    // tutorial section.
    printf("Generating drum_intro...\n");
    std::vector<DrumHit> drumIntroChart{
        {0.00, 0}, {2.00, 2}, {4.00, 0}, {6.00, 2},
    };
    std::vector<DrumHit> drumIntroAudio{
        {0.00, 0, 0.7}, {1.00, 2, 0.4}, {2.00, 2, 0.7}, {3.00, 2, 0.4},
        {4.00, 0, 0.7}, {5.00, 2, 0.4}, {6.00, 2, 0.7}, {7.00, 2, 0.4},
    };
    GenerateDrumClip(dir, "drum_intro", HumanizeDrums(drumIntroAudio, 7101u, 0.015, 0.15), drumIntroChart, 8.0,
                      secondsPerBeat, 5001u, 0.42, 0.15, 0.4);

    // drums: background-only soft kick/hihat/snare loop, brushed feel
    // (hihat carries the pulse, snare only lands as a gentle backbeat).
    printf("Generating drums (background only, no chart)...\n");
    std::vector<DrumHit> drumsAudio{
        {0.00, 0, 0.7}, {1.00, 2, 0.35}, {2.00, 2, 0.35}, {3.00, 2, 0.35}, {4.00, 1, 0.55}, {5.00, 2, 0.35},
        {6.00, 2, 0.35}, {7.00, 2, 0.35}, {8.00, 0, 0.7}, {9.00, 2, 0.35}, {10.00, 2, 0.35}, {11.00, 2, 0.35},
        {12.00, 1, 0.55}, {13.00, 2, 0.35}, {14.00, 2, 0.35}, {15.00, 2, 0.35},
    };
    GenerateDrumClip(dir, "drums", HumanizeDrums(drumsAudio, 7102u, 0.015, 0.15), {}, 16.0, secondsPerBeat, 5002u,
                      0.4, 0.15, 0.4);

    // drums_2: same brushed kit, a little more motion for the second half
    // of the song without ever getting busy.
    printf("Generating drums_2...\n");
    std::vector<DrumHit> drums2Chart{
        {0.00, 0}, {2.00, 1}, {4.00, 0}, {6.00, 2}, {8.00, 0}, {10.00, 1}, {12.00, 0}, {14.00, 2},
    };
    std::vector<DrumHit> drums2Audio{
        {0.00, 0, 0.7}, {1.00, 2, 0.35}, {2.00, 1, 0.55}, {3.00, 2, 0.35}, {4.00, 0, 0.7}, {5.00, 2, 0.35},
        {6.00, 2, 0.35}, {6.50, 2, 0.3}, {7.00, 2, 0.35}, {8.00, 0, 0.7}, {9.00, 2, 0.35}, {10.00, 1, 0.55},
        {11.00, 2, 0.35}, {12.00, 0, 0.7}, {13.00, 2, 0.35}, {14.00, 2, 0.35}, {14.50, 2, 0.3}, {15.00, 2, 0.35},
    };
    GenerateDrumClip(dir, "drums_2", HumanizeDrums(drums2Audio, 7103u, 0.015, 0.15), drums2Chart, 16.0, secondsPerBeat,
                      5003u, 0.4, 0.15, 0.4);

    // Bass: slow, mostly whole/half-note warm Bass-timbre roots under an
    // Am - F - C - G progression - nothing syncopated or busy.
    printf("Generating bass...\n");
    std::vector<MelodicEvent> bassEvents{
        {0.00, 1.8, 0, c_A2}, {4.00, 1.8, 3, c_F3}, {8.00, 1.8, 0, c_C3}, {12.00, 1.8, 2, c_G2},
    };
    std::vector<MelodicEvent> bassAudio{
        {0.00, 1.8, 0, c_A2}, {2.00, 1.8, 0, c_A2}, {4.00, 1.8, 3, c_F3}, {6.00, 1.8, 3, c_F3},
        {8.00, 1.8, 0, c_C3}, {10.00, 1.8, 0, c_C3}, {12.00, 1.8, 2, c_G2}, {14.00, 1.8, 2, c_G2},
    };
    GenerateMelodicClip(dir, "bass", Humanize(bassAudio, 7110u, 0.01, 0.08), bassEvents, 16.0, secondsPerBeat,
                         Timbre::Bass, 0.38, 0.05, 0.3);

    // Pad: slow-moving Bell-timbre chord pad (Am, F, C, G), the harmonic
    // bed the rest of the song sits on - long held notes, heavy reverb
    // send, quiet in the mix on purpose.
    printf("Generating pad...\n");
    std::vector<MelodicEvent> padEvents{
        {0.00, 3.8, 0, c_A3}, {4.00, 3.8, 3, c_F3}, {8.00, 3.8, 0, c_C4}, {12.00, 3.8, 2, c_G3},
    };
    GenerateMelodicClip(dir, "pad", Humanize(padEvents, 7111u, 0.015, 0.06), padEvents, 16.0, secondsPerBeat,
                         Timbre::Bell, 0.24, 0.32, 0.6);

    // Lead: gentle Triangle-timbre melody, mostly stepwise motion within
    // the A natural minor scale, generous space between phrases so nothing
    // ever feels rushed. Chart keeps only the phrase's strongest landings.
    printf("Generating lead...\n");
    std::vector<MelodicEvent> leadAudio{
        {0.50, 0.9, 0, c_A3}, {1.50, 0.9, 1, c_B3}, {2.50, 1.4, 2, c_C4}, {4.50, 0.9, 3, c_D4},
        {5.50, 0.9, 2, c_C4}, {6.50, 1.4, 1, c_B3}, {8.50, 0.9, 0, c_A3}, {9.50, 0.9, 2, c_C4},
        {10.50, 1.4, 3, c_D4}, {12.50, 0.9, 2, c_C4}, {13.50, 0.9, 1, c_B3}, {14.50, 1.4, 0, c_A3},
    };
    std::vector<MelodicEvent> leadChart{
        {0.50, 1.4, 0, c_A3}, {2.50, 1.4, 2, c_C4}, {4.50, 1.4, 3, c_D4}, {6.50, 1.4, 1, c_B3},
        {8.50, 1.4, 0, c_A3}, {10.50, 1.4, 3, c_D4}, {12.50, 1.4, 2, c_C4}, {14.50, 1.4, 0, c_A3},
    };
    GenerateMelodicClip(dir, "lead", Humanize(leadAudio, 7112u, 0.012, 0.1), leadChart, 16.0, secondsPerBeat,
                         Timbre::Triangle, 0.36, 0.24, 0.45);

    // Lead 2: answering phrase, same gentle treatment, sits a third above
    // lead's register without ever colliding with it.
    printf("Generating lead_2...\n");
    std::vector<MelodicEvent> lead2Audio{
        {0.50, 0.9, 2, c_C4}, {1.50, 0.9, 3, c_D4}, {2.50, 1.4, 2, c_C4}, {4.50, 0.9, 1, c_B3},
        {5.50, 0.9, 2, c_C4}, {6.50, 1.4, 0, c_A3}, {8.50, 0.9, 2, c_C4}, {9.50, 0.9, 3, c_D4},
        {10.50, 1.4, 2, c_E4}, {12.50, 0.9, 1, c_B3}, {13.50, 0.9, 2, c_C4}, {14.50, 1.4, 1, c_B3},
    };
    std::vector<MelodicEvent> lead2Chart{
        {0.50, 1.4, 2, c_C4}, {2.50, 1.4, 2, c_C4}, {4.50, 1.4, 1, c_B3}, {6.50, 1.4, 0, c_A3},
        {8.50, 1.4, 2, c_C4}, {10.50, 1.4, 3, c_E4}, {12.50, 1.4, 1, c_B3}, {14.50, 1.4, 1, c_B3},
    };
    GenerateMelodicClip(dir, "lead_2", Humanize(lead2Audio, 7113u, 0.012, 0.1), lead2Chart, 16.0, secondsPerBeat,
                         Timbre::Triangle, 0.36, 0.24, 0.45);

    // Bridge: DontFail, forgiving - a slow Bell arpeggio through the same
    // four chords, meant purely to be pretty and easy, mirroring how
    // Byte Blaster's bell_bridge is used.
    printf("Generating bridge (DontFail)...\n");
    std::vector<MelodicEvent> bridgeEvents{
        {0.00, 1.6, 0, c_A3}, {2.00, 1.6, 2, c_C4}, {4.00, 3.6, 1, c_E4},
        {8.00, 1.6, 3, c_F3}, {10.00, 1.6, 0, c_A3}, {12.00, 3.6, 2, c_C4},
        {16.00, 1.6, 0, c_C4}, {18.00, 1.6, 1, c_E4}, {20.00, 3.6, 2, c_G4},
        {24.00, 1.6, 2, c_G3}, {26.00, 1.6, 1, c_B3}, {28.00, 3.6, 3, c_D4},
    };
    GenerateMelodicClip(dir, "bridge", Humanize(bridgeEvents, 7114u, 0.015, 0.08), bridgeEvents, 32.0, secondsPerBeat,
                         Timbre::Bell, 0.3, 0.34, 0.6);
}

int main()
{
    GenerateByteBlaster();
    GenerateVoltageRun();
    GenerateQuietHours();
    printf("Done.\n");
    return 0;
}
