// Song content generator - a reusable little synth + Standard MIDI File
// writer for producing a chart's .wav/.mid pairs from code instead of real
// recordings: square/triangle/bell tones for melodic clips, noise+sine
// drum hits for percussion, all mixed and written as plain 16-bit mono PCM
// WAV, plus (for judged clips) a matching note chart using the engine's
// four fixed lane pitches (kLaneMidiPitches in src/LaneConfig.h - keep this
// in sync if that ever changes). Deterministic: the noise generator is a
// seeded LCG, so re-running produces byte-identical output.
//
// Not wired into CMakeLists.txt (it has no dependency on the engine at
// all, just the C++ standard library) - compile and run it directly:
//   g++ -O2 -std=c++20 -o song_gen.exe tools/SongGenerator.cpp
//   ./song_gen.exe        (run from the repo root - paths are relative to it)
//
// Everything above main() is the reusable part (WAV/MIDI writers, DSP
// helpers, the Mixer, the drum/melodic voice renderers, GenerateDrumClip/
// GenerateMelodicClip). To author a new song, keep all of that and replace
// main()'s own note-event tables/clip list with the new song's - see
// Content/Byte Blaster (AI Slop)/Byte Blaster.chart for the [song]/[clip]/
// section text this main() was written to match (that file isn't
// generated by this tool - it's still hand-authored, same as any other
// chart).
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace
{

constexpr int kSampleRate = 44100;
constexpr double kBpm = 150.0;
constexpr double kSecondsPerBeat = 60.0 / kBpm;
constexpr int kTicksPerQuarter = 480;
constexpr int kLaneMidiPitches[4] = {72, 74, 76, 77};

// ---------- WAV writer ----------

void WriteWavMono16(const std::string& path, const std::vector<int16_t>& samples)
{
    std::ofstream f(path, std::ios::binary);
    uint32_t dataBytes = static_cast<uint32_t>(samples.size() * sizeof(int16_t));
    uint32_t riffSize = 36 + dataBytes;
    uint16_t formatTag = 1; // PCM
    uint16_t channels = 1;
    uint32_t sampleRate = kSampleRate;
    uint16_t bitsPerSample = 16;
    uint16_t blockAlign = channels * bitsPerSample / 8;
    uint32_t byteRate = sampleRate * blockAlign;
    uint32_t fmtSize = 16;

    f.write("RIFF", 4);
    f.write(reinterpret_cast<const char*>(&riffSize), 4);
    f.write("WAVE", 4);
    f.write("fmt ", 4);
    f.write(reinterpret_cast<const char*>(&fmtSize), 4);
    f.write(reinterpret_cast<const char*>(&formatTag), 2);
    f.write(reinterpret_cast<const char*>(&channels), 2);
    f.write(reinterpret_cast<const char*>(&sampleRate), 4);
    f.write(reinterpret_cast<const char*>(&byteRate), 4);
    f.write(reinterpret_cast<const char*>(&blockAlign), 2);
    f.write(reinterpret_cast<const char*>(&bitsPerSample), 2);
    f.write("data", 4);
    f.write(reinterpret_cast<const char*>(&dataBytes), 4);
    f.write(reinterpret_cast<const char*>(samples.data()), dataBytes);
}

// ---------- MIDI writer ----------

void WriteVLQ(std::vector<uint8_t>& out, uint32_t value)
{
    uint8_t buffer[4];
    int count = 0;
    buffer[count++] = static_cast<uint8_t>(value & 0x7F);
    value >>= 7;
    while (value > 0)
    {
        buffer[count++] = static_cast<uint8_t>(value & 0x7F);
        value >>= 7;
    }
    for (int i = count - 1; i >= 0; --i)
    {
        uint8_t b = buffer[i];
        if (i != 0)
        {
            b |= 0x80;
        }
        out.push_back(b);
    }
}

void WriteBE32(std::ofstream& f, uint32_t v)
{
    uint8_t b[4] = {static_cast<uint8_t>(v >> 24), static_cast<uint8_t>(v >> 16), static_cast<uint8_t>(v >> 8),
                     static_cast<uint8_t>(v)};
    f.write(reinterpret_cast<const char*>(b), 4);
}

void WriteBE16(std::ofstream& f, uint16_t v)
{
    uint8_t b[2] = {static_cast<uint8_t>(v >> 8), static_cast<uint8_t>(v)};
    f.write(reinterpret_cast<const char*>(b), 2);
}

struct MidiNote
{
    int startTick = 0;
    int endTick = 0;
    int pitch = 0;
};

void WriteMidiFile(const std::string& path, const std::vector<MidiNote>& notes, int totalTicks)
{
    struct RawEvent
    {
        int tick;
        bool isOn;
        int pitch;
    };
    std::vector<RawEvent> events;
    events.reserve(notes.size() * 2);
    for (const MidiNote& n : notes)
    {
        events.push_back({n.startTick, true, n.pitch});
        events.push_back({n.endTick, false, n.pitch});
    }
    std::stable_sort(events.begin(), events.end(),
                      [](const RawEvent& a, const RawEvent& b)
                      {
                          if (a.tick != b.tick)
                          {
                              return a.tick < b.tick;
                          }
                          // Note-offs before note-ons at the same tick, so a
                          // back-to-back same-pitch/lane repeat never reads
                          // as a zero-length overlap.
                          return !a.isOn && b.isOn;
                      });

    std::vector<uint8_t> track;
    int prevTick = 0;
    for (const RawEvent& e : events)
    {
        WriteVLQ(track, static_cast<uint32_t>(e.tick - prevTick));
        prevTick = e.tick;
        track.push_back(e.isOn ? 0x90 : 0x80);
        track.push_back(static_cast<uint8_t>(e.pitch));
        track.push_back(e.isOn ? 100 : 64);
    }
    // End-of-track meta event, placed at totalTicks (not just the last
    // note's own end) so the pattern's declared length matches the audio's
    // full loop instead of shrinking to whatever the last note happened to
    // end on.
    WriteVLQ(track, static_cast<uint32_t>(std::max(0, totalTicks - prevTick)));
    track.push_back(0xFF);
    track.push_back(0x2F);
    track.push_back(0x00);

    std::ofstream f(path, std::ios::binary);
    f.write("MThd", 4);
    WriteBE32(f, 6);
    WriteBE16(f, 0); // format 0: single track
    WriteBE16(f, 1); // ntrks
    WriteBE16(f, static_cast<uint16_t>(kTicksPerQuarter));
    f.write("MTrk", 4);
    WriteBE32(f, static_cast<uint32_t>(track.size()));
    f.write(reinterpret_cast<const char*>(track.data()), static_cast<std::streamsize>(track.size()));
}

// ---------- DSP ----------

// Deterministic LCG noise so re-running the generator reproduces byte-
// identical output.
double NoiseSample(uint32_t& state)
{
    state = state * 1664525u + 1013904223u;
    return (static_cast<double>(state) / 4294967295.0) * 2.0 - 1.0;
}

double Square(double phase)
{
    return std::fmod(phase, 1.0) < 0.5 ? 1.0 : -1.0;
}

double Triangle(double phase)
{
    double p = std::fmod(phase, 1.0);
    return p < 0.5 ? (4.0 * p - 1.0) : (3.0 - 4.0 * p);
}

// One-pole low-pass; alpha in (0,1], smaller = darker.
double OnePoleLowPass(double x, double& state, double alpha)
{
    state += alpha * (x - state);
    return state;
}

struct Mixer
{
    std::vector<double> buffer; // -1..1 range, additive

    explicit Mixer(int totalSamples) : buffer(static_cast<size_t>(totalSamples), 0.0)
    {
    }

    void Add(int startSample, const std::vector<double>& voice)
    {
        for (size_t i = 0; i < voice.size(); ++i)
        {
            size_t idx = static_cast<size_t>(startSample) + i;
            if (idx < buffer.size())
            {
                buffer[idx] += voice[i];
            }
        }
    }

    std::vector<int16_t> ToPcm16(double targetPeak = 0.92) const
    {
        double peak = 1e-6;
        for (double v : buffer)
        {
            peak = std::max(peak, std::abs(v));
        }
        double scale = peak > targetPeak ? (targetPeak / peak) : 1.0;
        std::vector<int16_t> out(buffer.size());
        for (size_t i = 0; i < buffer.size(); ++i)
        {
            double v = std::clamp(buffer[i] * scale, -1.0, 1.0);
            out[i] = static_cast<int16_t>(std::lround(v * 32767.0));
        }
        return out;
    }
};

// ---------- Instrument voices ----------

// Percussive drum hit rendered straight into a fresh vector, added into the
// mixer at the event's own start sample - envelope length is the drum's own
// natural decay, independent of however short the chart's own tap-note
// duration is (a real drum's sound outlasts a quick press/release gesture).
std::vector<double> RenderKick(uint32_t& noiseState)
{
    int n = static_cast<int>(0.20 * kSampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(kSampleRate);
        double freq = 150.0 * std::exp(-t * 28.0) + 48.0; // pitch sweep, high -> low
        double phase = std::fmod(t * freq, 1.0);
        double tone = std::sin(2.0 * 3.14159265358979 * phase);
        double amp = std::exp(-t * 16.0);
        double click = (t < 0.004) ? NoiseSample(noiseState) * (1.0 - t / 0.004) * 0.35 : 0.0;
        v[static_cast<size_t>(i)] = (tone * amp + click) * 0.9;
    }
    return v;
}

std::vector<double> RenderSnare(uint32_t& noiseState)
{
    int n = static_cast<int>(0.16 * kSampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    double hp = 0.0;
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(kSampleRate);
        double noise = NoiseSample(noiseState);
        double lp = 0.0;
        static thread_local double lpState = 0.0;
        (void)lp;
        lpState += 0.5 * (noise - lpState);
        double highPassed = noise - lpState; // crude high-pass: original minus a low-passed copy
        (void)hp;
        double noiseAmp = std::exp(-t * 24.0);
        double tone = std::sin(2.0 * 3.14159265358979 * 190.0 * t) * std::exp(-t * 30.0);
        v[static_cast<size_t>(i)] = (highPassed * 0.7 * noiseAmp + tone * 0.5) * 0.8;
    }
    return v;
}

std::vector<double> RenderHihat(uint32_t& noiseState)
{
    int n = static_cast<int>(0.06 * kSampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    double lp1 = 0.0, lp2 = 0.0;
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(kSampleRate);
        double noise = NoiseSample(noiseState);
        lp1 = OnePoleLowPass(noise, lp1, 0.35);
        lp2 = OnePoleLowPass(lp1, lp2, 0.35);
        double highPassed = noise - lp2; // two cascaded LPs subtracted out -> steeper high-pass
        double amp = std::exp(-t * 55.0);
        v[static_cast<size_t>(i)] = highPassed * amp * 0.55;
    }
    return v;
}

std::vector<double> RenderTom(uint32_t& noiseState)
{
    int n = static_cast<int>(0.18 * kSampleRate);
    std::vector<double> v(static_cast<size_t>(n));
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(kSampleRate);
        double freq = 300.0 * std::exp(-t * 14.0) + 130.0;
        double phase = std::fmod(t * freq, 1.0);
        double tone = std::sin(2.0 * 3.14159265358979 * phase);
        double amp = std::exp(-t * 13.0);
        double noise = NoiseSample(noiseState) * 0.08 * std::exp(-t * 40.0);
        v[static_cast<size_t>(i)] = (tone * amp + noise) * 0.85;
    }
    return v;
}

enum class Timbre
{
    Square,
    Triangle,
    Bell,
};

// Melodic note - length follows the chart's own note duration (in
// seconds), giving a short envelope with a bit of release tail so back-to-
// back staccato notes never click.
std::vector<double> RenderMelodicNote(double freqHz, double durationSeconds, Timbre timbre)
{
    double releaseSeconds = (timbre == Timbre::Bell) ? 0.45 : 0.05;
    int n = static_cast<int>((durationSeconds + releaseSeconds) * kSampleRate);
    n = std::max(n, 8);
    std::vector<double> v(static_cast<size_t>(n));
    double attackSeconds = (timbre == Timbre::Bell) ? 0.01 : 0.004;
    for (int i = 0; i < n; ++i)
    {
        double t = i / static_cast<double>(kSampleRate);
        double env;
        if (t < attackSeconds)
        {
            env = t / attackSeconds;
        }
        else if (t < durationSeconds)
        {
            env = (timbre == Timbre::Bell) ? std::exp(-(t - attackSeconds) * 1.2) : 0.85;
        }
        else
        {
            double releaseT = t - durationSeconds;
            double sustainLevel = (timbre == Timbre::Bell) ? std::exp(-(durationSeconds - attackSeconds) * 1.2) : 0.85;
            env = sustainLevel * std::exp(-releaseT / (releaseSeconds * 0.35));
        }

        double sample = 0.0;
        if (timbre == Timbre::Square)
        {
            sample = Square(t * freqHz) * 0.5;
        }
        else if (timbre == Timbre::Triangle)
        {
            sample = Triangle(t * freqHz) * 0.6;
        }
        else // Bell
        {
            sample = std::sin(2.0 * 3.14159265358979 * freqHz * t) * 0.5 +
                     std::sin(2.0 * 3.14159265358979 * freqHz * 2.01 * t) * 0.18 +
                     std::sin(2.0 * 3.14159265358979 * freqHz * 3.0 * t) * 0.08;
        }
        v[static_cast<size_t>(i)] = sample * env;
    }
    return v;
}

// ---------- Clip data model ----------

enum class DrumPart
{
    Kick,
    Snare,
    Hihat,
    Tom,
};

struct DrumHit
{
    double beat;
    int lane; // also selects the part: 0=kick,1=snare,2=hihat,3=tom
};

struct MelodicEvent
{
    double beat;
    double durationBeats;
    int lane;
    double freqHz;
};

// Renders a drum-pattern clip's audio and (unless backgroundOnly) its note
// chart, both derived from the same event list so what the player sees is
// exactly what they hear.
void GenerateDrumClip(const std::string& dir, const std::string& name, const std::vector<DrumHit>& hits,
                       double totalBeats, bool emitMidi, uint32_t noiseSeed)
{
    int totalSamples = static_cast<int>(std::lround(totalBeats * kSecondsPerBeat * kSampleRate));
    Mixer mixer(totalSamples);
    uint32_t noiseState = noiseSeed;

    std::vector<MidiNote> notes;
    for (const DrumHit& h : hits)
    {
        int startSample = static_cast<int>(std::lround(h.beat * kSecondsPerBeat * kSampleRate));
        std::vector<double> voice;
        switch (h.lane)
        {
            case 0:
                voice = RenderKick(noiseState);
                break;
            case 1:
                voice = RenderSnare(noiseState);
                break;
            case 2:
                voice = RenderHihat(noiseState);
                break;
            default:
                voice = RenderTom(noiseState);
                break;
        }
        mixer.Add(startSample, voice);

        if (emitMidi)
        {
            int startTick = static_cast<int>(std::lround(h.beat * kTicksPerQuarter));
            int endTick = startTick + static_cast<int>(std::lround(0.15 * kTicksPerQuarter));
            notes.push_back({startTick, endTick, kLaneMidiPitches[h.lane]});
        }
    }

    WriteWavMono16(dir + "/" + name + ".wav", mixer.ToPcm16());
    if (emitMidi)
    {
        int totalTicks = static_cast<int>(std::lround(totalBeats * kTicksPerQuarter));
        WriteMidiFile(dir + "/" + name + ".mid", notes, totalTicks);
        printf("  %s: %d drum hits, %.2fs, %d ticks\n", name.c_str(), (int)hits.size(),
               totalBeats * kSecondsPerBeat, totalTicks);
    }
    else
    {
        printf("  %s: %d drum hits (background, no chart), %.2fs\n", name.c_str(), (int)hits.size(),
               totalBeats * kSecondsPerBeat);
    }
}

void GenerateMelodicClip(const std::string& dir, const std::string& name, const std::vector<MelodicEvent>& events,
                          double totalBeats, Timbre timbre)
{
    int totalSamples = static_cast<int>(std::lround(totalBeats * kSecondsPerBeat * kSampleRate));
    Mixer mixer(totalSamples);

    std::vector<MidiNote> notes;
    for (const MelodicEvent& e : events)
    {
        int startSample = static_cast<int>(std::lround(e.beat * kSecondsPerBeat * kSampleRate));
        std::vector<double> voice = RenderMelodicNote(e.freqHz, e.durationBeats * kSecondsPerBeat, timbre);
        mixer.Add(startSample, voice);

        int startTick = static_cast<int>(std::lround(e.beat * kTicksPerQuarter));
        int endTick = static_cast<int>(std::lround((e.beat + e.durationBeats) * kTicksPerQuarter));
        notes.push_back({startTick, endTick, kLaneMidiPitches[e.lane]});
    }

    WriteWavMono16(dir + "/" + name + ".wav", mixer.ToPcm16());
    int totalTicks = static_cast<int>(std::lround(totalBeats * kTicksPerQuarter));
    WriteMidiFile(dir + "/" + name + ".mid", notes, totalTicks);
    printf("  %s: %d notes, %.2fs, %d ticks\n", name.c_str(), (int)events.size(), totalBeats * kSecondsPerBeat,
           totalTicks);
}

// ---------- Note-name frequency helpers (A4 = 440Hz equal temperament) ----------
constexpr double kC2 = 65.406, kG2 = 97.999, kA2 = 110.000, kB2 = 123.471, kC3 = 130.813, kD3 = 146.832,
                  kE3 = 164.814, kF3 = 174.614, kG3 = 195.998, kA3 = 220.000;
constexpr double kC4 = 261.626, kD4 = 293.665, kE4 = 329.628, kF4 = 349.228, kG4 = 391.995, kA4 = 440.000,
                  kB4 = 493.883;
constexpr double kC5 = 523.251, kD5 = 587.330, kE5 = 659.255, kG5 = 783.991;

} // namespace

int main()
{
    std::string dir = "Content/Byte Blaster (AI Slop)";

    printf("Generating drum_intro...\n");
    GenerateDrumClip(dir, "drum_intro",
                      {
                          {0.00, 0}, {1.00, 0}, {1.50, 2}, {2.00, 1}, {3.00, 0}, {3.50, 2},
                          {4.00, 0}, {4.50, 0}, {5.00, 1}, {5.50, 2}, {6.00, 0}, {6.50, 2},
                          {7.00, 1}, {7.25, 3}, {7.50, 3}, {7.75, 0},
                      },
                      8.0, /*emitMidi=*/true, 1001u);

    printf("Generating drums (background only, no chart)...\n");
    GenerateDrumClip(dir, "drums",
                      {
                          {0.00, 0}, {0.50, 2}, {1.00, 1}, {1.50, 2}, {2.00, 0}, {2.50, 2}, {3.00, 1}, {3.50, 2},
                          {4.00, 0}, {4.50, 2}, {5.00, 1}, {5.50, 2}, {6.00, 0}, {6.50, 2}, {7.00, 1}, {7.25, 3},
                          {7.50, 3}, {7.75, 3},
                      },
                      8.0, /*emitMidi=*/false, 2002u);

    printf("Generating drums_2...\n");
    GenerateDrumClip(dir, "drums_2",
                      {
                          {0.00, 0}, {0.75, 0}, {1.00, 1}, {1.50, 2}, {2.00, 0}, {2.25, 0}, {2.75, 2}, {3.00, 1},
                          {3.50, 2}, {3.75, 0}, {4.00, 0}, {4.50, 2}, {5.00, 1}, {5.25, 3}, {5.50, 2}, {6.00, 0},
                          {6.50, 0}, {6.75, 2}, {7.00, 1}, {7.25, 3}, {7.50, 3}, {7.75, 0},
                      },
                      8.0, /*emitMidi=*/true, 3003u);

    printf("Generating bass...\n");
    GenerateMelodicClip(dir, "bass",
                         {
                             {0.00, 0.40, 0, kC3}, {0.75, 0.40, 0, kC3}, {1.50, 0.40, 1, kG2}, {2.00, 0.40, 0, kC3},
                             {2.75, 0.40, 2, kE3}, {3.50, 0.40, 0, kC3}, {4.00, 0.40, 2, kG2}, {4.75, 0.40, 2, kG2},
                             {5.50, 0.40, 3, kD3}, {6.00, 0.40, 2, kG2}, {6.75, 0.40, 1, kB2}, {7.50, 0.40, 2, kG2},
                         },
                         8.0, Timbre::Square);

    printf("Generating arp...\n");
    {
        std::vector<MelodicEvent> arpEvents;
        double cChord[4] = {kC4, kE4, kG4, kC5};
        double gChord[4] = {kG4, kB4, kD5, kC5 * (783.991 / 523.251)}; // G4,B4,D5,G5
        for (int bar = 0; bar < 2; ++bar)
        {
            const double* chord = (bar == 0) ? cChord : gChord;
            for (int step = 0; step < 16; ++step)
            {
                double beat = bar * 4.0 + step * 0.25;
                int lane = step % 4;
                arpEvents.push_back({beat, 0.18, lane, chord[lane]});
            }
        }
        GenerateMelodicClip(dir, "arp", arpEvents, 8.0, Timbre::Triangle);
    }

    printf("Generating lead...\n");
    GenerateMelodicClip(dir, "lead",
                         {
                             {0.00, 0.5, 0, kE4}, {0.50, 0.5, 1, kG4}, {1.00, 0.5, 2, kA4}, {1.50, 0.5, 1, kG4},
                             {2.00, 1.0, 3, kC5}, {3.00, 0.75, 2, kB4}, {3.75, 0.25, 2, kA4}, {4.00, 0.5, 1, kG4},
                             {4.50, 0.5, 0, kE4}, {5.00, 0.5, 0, kD4}, {5.50, 0.5, 0, kE4}, {6.00, 1.0, 1, kG4},
                             {7.00, 0.5, 1, kF4}, {7.50, 0.5, 0, kE4},
                         },
                         8.0, Timbre::Square);

    printf("Generating lead_2...\n");
    GenerateMelodicClip(dir, "lead_2",
                         {
                             {0.00, 0.5, 2, kA4}, {0.50, 0.5, 3, kC5}, {1.00, 0.5, 3, kE5}, {1.50, 0.5, 3, kC5},
                             {2.00, 1.0, 2, kA4}, {3.00, 0.5, 1, kG4}, {3.50, 0.5, 2, kA4}, {4.00, 0.5, 0, kF4},
                             {4.50, 0.5, 2, kA4}, {5.00, 0.5, 3, kC5}, {5.50, 0.5, 2, kA4}, {6.00, 1.0, 0, kF4},
                             {7.00, 0.5, 1, kG4}, {7.50, 0.5, 2, kA4},
                         },
                         8.0, Timbre::Square);

    printf("Generating bell_bridge (DontFail)...\n");
    GenerateMelodicClip(dir, "bell_bridge",
                         {
                             {0.00, 0.8, 2, kA4}, {1.00, 0.8, 3, kC5}, {2.00, 1.8, 3, kE5},
                             {4.00, 0.8, 1, kF4}, {5.00, 0.8, 2, kA4}, {6.00, 1.8, 3, kC5},
                             {8.00, 0.8, 0, kC4}, {9.00, 0.8, 1, kE4}, {10.00, 1.8, 1, kG4},
                             {12.00, 0.8, 1, kG4}, {13.00, 0.8, 2, kB4}, {14.00, 1.8, 3, kD5},
                         },
                         16.0, Timbre::Bell);

    printf("Done.\n");
    return 0;
}
